apiVersion: apps/v1
kind: Deployment
metadata:
  name: demucs-worker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demucs-worker
  template:
    metadata:
      labels:
        app: demucs-worker
    spec:
      containers:
      - name: demucs-worker
        image: iamadisri/demucs-worker:latest
        resources:
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
          - containerPort: 6000
        env:
          - name: MINIO_HOST
            value: "minio"
          - name: MINIO_PORT
            value: "9000"
          - name: MINIO_USER
            value: "rootuser"
          - name: MINIO_PASSWD
            value: "rootpass123"
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: "GET_HOSTS_FROM"
            value: "dns"
        